name: flutter_base_template
description: 'A new Flutter Template project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

isar_version: &isar_version 3.1.0+1

dependencies:
  flutter:
    sdk: flutter
  devicelocale: ^0.7.0
  easy_localization: ^3.0.3
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  ionicons: ^0.2.2
  equatable: ^2.0.5
  recase: ^4.1.0
  country_flags: ^2.2.0
  package_info_plus: ^5.0.1
  flutter_launcher_icons: ^0.13.1
  resonance: ^1.0.3
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  isar_generator: *isar_version

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/languages/

flutter_launcher_icons:
  # Global/Package Side Settings
  # https://pub.dev/packages/flutter_launcher_icons#mag-attributes
  image_path: 'assets/images/app_icon.png'

  # Android Side Settings
  # https://pub.dev/packages/flutter_launcher_icons#android
  android: true
  min_sdk_android: 23 # template default, min 16, package default 21

  # IOS Side Settings
  # https://pub.dev/packages/flutter_launcher_icons#ios
  ios: true
